Encore plus de robustesses dans le script de mises à jour (espace disque)

diff --git a/search-cron b/search-cron
--- a/search-cron
+++ b/search-cron
@@ -1,22 +1,34 @@
 #!/bin/sh
 
+MUST_REMAIN_SPACE=500000 # 500 Mb
 SCRIPTS_DIR=`dirname "${0}"`
 CRAWL_SCRIPT=$SCRIPTS_DIR/crawl
 REINDEX_SCRIPT=$SCRIPTS_DIR/reindex
 
 do_core() {
-    # Create a backup of the crawl DB, just in case
-    cp -R $HOME/crawl-${1} $BACKUPS_DIR/crawl-${1}-$DATE
-    if [ $? -ne 0 ]; then
+    CRAWLDB_DIR=$HOME/crawl-${1}
+    CRAWLDB_SIZE=`du --max-depth=0 $CRAWLDB_DIR | awk '{print $1}'`
+    SPACE_LEFT=`df -k $HOME | tail -1 | awk '{print $4}'`
+    REMAINING_SIZE=$(($SPACE_LEFT - $CRAWLDB_SIZE))
+
+    BACKUP_OUT_LOG=$LOGS_DIR/${DATE}-OUT-backup-${1}.log
+    BACKUP_ERR_LOG=$LOGS_DIR/${DATE}-ERROR-backup-${1}.log
+    CRAWL_OUT_LOG=$LOGS_DIR/${DATE}-OUT-crawl-${1}.log
+    CRAWL_ERR_LOG=$LOGS_DIR/${DATE}-ERROR-crawl-${1}.log
+    REINDEX_OUT_LOG=$LOGS_DIR/${DATE}-OUT-reindex-${1}.log
+    REINDEX_ERR_LOG=$LOGS_DIR/${DATE}-ERROR-reindex-${1}.log
+
+    if [ $REMAINING_SIZE -le $MUST_REMAIN_SPACE ]; then
         echo "${1}: Not enough space to create the backup";
+        return 1;
+    fi
+    # Create a backup of the crawl DB, just in case
+    cp -R $CRAWLDB_DIR $BACKUPS_DIR/crawl-${1}-$DATE > $BACKUP_OUT_LOG 2> $BACKUP_ERR_LOG;
+    if [ $? -ne 0 ]; then
+        echo "${1}: Backup failed";
         rm -rf $BACKUPS_DIR/crawl-${1}-$DATE;
         return 1;
     fi
-
-    CRAWL_OUT_LOG=$LOGS_DIR/OUT-crawl-${1}-$DATE.log
-    CRAWL_ERR_LOG=$LOGS_DIR/ERROR-crawl-${1}-$DATE.log
-    REINDEX_OUT_LOG=$LOGS_DIR/OUT-reindex-${1}-$DATE.log
-    REINDEX_ERR_LOG=$LOGS_DIR/ERROR-reindex-${1}-$DATE.log
 
     # Crawl the website
     $CRAWL_SCRIPT $1 > $CRAWL_OUT_LOG 2> $CRAWL_ERR_LOG;
@@ -57,6 +69,14 @@ check_status() {
     fi
 }
 
+cleanup() {
+    # The Hadoop tmp directory can take all available space
+    HADOOP_TMP_DIR=/tmp/hadoop-$USER
+    if [ -e $HADOOP_TMP_DIR ]; then
+        rm -rf $HADOOP_TMP_DIR;
+    fi
+}
+
 LOGS_DIR=$1
 BACKUPS_DIR=$2
 if [ "$1" = "" ] || [ "$2" = "" ]; then
@@ -71,12 +91,7 @@ else
 
     DATE=`date +\%Y-\%m-\%d-\%H\%M`
 
-    do_core rq-fr; check_status;
-    do_core rq-en; check_status;
-
-    # The Hadoop tmp directory can take all available space
-    HADOOP_TMP_DIR=/tmp/hadoop-$USER
-    if [ -e $HADOOP_TMP_DIR ]; then
-        rm -rf $HADOOP_TMP_DIR;
-    fi
+    cleanup;
+    do_core rq-fr; cleanup;
+    do_core rq-en; cleanup;
 fi
