Plus de robustesses dans le script de mise à jour

diff --git a/search-cron b/search-cron
--- a/search-cron
+++ b/search-cron
@@ -7,6 +7,11 @@ REINDEX_SCRIPT=$SCRIPTS_DIR/reindex
 do_core() {
     # Create a backup of the crawl DB, just in case
     cp -R $HOME/crawl-${1} $BACKUPS_DIR/crawl-${1}-$DATE
+    if [ $? -ne 0 ]; then
+        echo "${1}: Not enough space to create the backup";
+        rm -rf $BACKUPS_DIR/crawl-${1}-$DATE;
+        return 1;
+    fi
 
     CRAWL_OUT_LOG=$LOGS_DIR/OUT-crawl-${1}-$DATE.log
     CRAWL_ERR_LOG=$LOGS_DIR/ERROR-crawl-${1}-$DATE.log
@@ -14,37 +19,41 @@ do_core() {
     REINDEX_ERR_LOG=$LOGS_DIR/ERROR-reindex-${1}-$DATE.log
 
     # Crawl the website
-    $CRAWL_SCRIPT $1 > $CRAWL_OUT_LOG 2> $CRAWL_ERR_LOG
+    $CRAWL_SCRIPT $1 > $CRAWL_OUT_LOG 2> $CRAWL_ERR_LOG;
     RET_CODE=$?
     # Delete the error log if it is empty
     if [ ! -s $CRAWL_ERR_LOG ]; then
-        rm -rf $CRAWL_ERR_LOG
+        rm -rf $CRAWL_ERR_LOG;
     fi
 
     # If an error happened while crawling the website, we must restore the crawldb directory from a backup
     if [ $RET_CODE -ne 0 ]; then
-        echo "${1}: Crawl failed, restoring backup"
-        rm -rf $HOME/crawl-${1}
-        mv $BACKUPS_DIR/crawl-${1}-$DATE $HOME/crawl-${1}
+        echo "${1}: Crawl failed, restoring backup";
+        rm -rf $HOME/crawl-${1};
+        mv $BACKUPS_DIR/crawl-${1}-$DATE $HOME/crawl-${1};
+        return 1;
     else
         # Reindex all pages
-        # This deletes everything from the Solr index, so there is
-        #  a maximum of 5 tries before giving up
-        for I in 1 2 3 4 5; do
-            $REINDEX_SCRIPT $1 > $REINDEX_OUT_LOG 2> $REINDEX_ERR_LOG
-            RET_CODE=$?
+        $REINDEX_SCRIPT $1 > $REINDEX_OUT_LOG 2> $REINDEX_ERR_LOG
+        RET_CODE=$?
 
-            # Check if we must retry the reindexation
-            if [ $RET_CODE -eq 0 ]; then
-                # Delete the error log if it is empty
-                if [ ! -s $REINDEX_ERR_LOG ]; then
-                    rm -rf $REINDEX_ERR_LOG
-                fi
-                break
+        # Check if reindexation failed
+        if [ $RET_CODE -eq 0 ]; then
+            # Delete the error log if it is empty
+            if [ ! -s $REINDEX_ERR_LOG ]; then
+                rm -rf $REINDEX_ERR_LOG;
             fi
+        else
+            echo "${1}: Reindexation failed";
+            return 1;
+        fi
+    fi
+}
 
-            echo "${1}: Reindexation (${I} of 5) failed, trying again"
-        done
+check_status() {
+    RETCODE=$?;
+    if [ $RETCODE -ne 0 ]; then
+        exit $RETCODE
     fi
 }
 
@@ -54,14 +63,20 @@ if [ "$1" = "" ] || [ "$2" = "" ]; then
     echo "You must provide the path to the logs and backups directories (ex: ./search-cron ./logs ./backups)"
 else
     if [ ! -e $LOGS_DIR ]; then
-        mkdir -p $LOGS_DIR
+        mkdir -p $LOGS_DIR; check_status;
     fi
     if [ ! -e $BACKUPS_DIR ]; then
-        mkdir -p $BACKUPS_DIR
+        mkdir -p $BACKUPS_DIR; check_status;
     fi
 
     DATE=`date +\%Y-\%m-\%d-\%H\%M`
 
-    do_core rq-fr
-    do_core rq-en
+    do_core rq-fr; check_status;
+    do_core rq-en; check_status;
+
+    # The Hadoop tmp directory can take all available space
+    HADOOP_TMP_DIR=/tmp/hadoop-$USER
+    if [ -e $HADOOP_TMP_DIR ]; then
+        rm -rf $HADOOP_TMP_DIR;
+    fi
 fi
